(WIP) Added docker-compose config to standup local elasticsearch config
liatrio/grafeas-elasticsearch pull request #1
Opened 2020-11-11 21:48 UTC by gesparza3

This PR adds a docker-compose file to standup a local instance of Grafeas and Elasticsearch to aid in developing an Elasticsearch backend for Grafeas. As a part of initalization for Elastic a Grafeas user is created for storage.

2020-11-11 22:01 UTC, ChrisSchreiber requested changes

2020-11-11 22:04 UTC, gesparza3 commented on Dockerfile
>  RUN apt-get update
Right you are...removed it altogether

2020-11-13 19:10 UTC, gesparza3 commented on go/v1beta1/main/main.go
> +			"http://db:9200",
Left these hardcoded for now until we decide on whether or not to restructure this project or instantiate Grafeas in another way.

2020-11-13 20:22 UTC, mrparkers approved these changes

2020-11-13 20:22 UTC, merged